# Generated by Django 4.2.2 on 2023-07-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibrosApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='codigo',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='libros',
            name='estado',
            field=models.CharField(max_length=100),
        ),
    ]
